<a href="https://colab.research.google.com/github/SUPERMOSCO/Capstone_Project_Customer_Churn/blob/main/Analyzing_Airline_Dataset_with_Python(Project)_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data=pd.read_csv('/content/airlines_flights_data.csv')
data.head(5)

In [ ]:
data.shape

In [ ]:
data.drop(columns='index',inplace=True)
data.head(5)

In [ ]:
data.isnull().sum()

In [ ]:
data.info()

In [ ]:
data.describe()

In [ ]:
data[data['price']==123071.000000]   # Details of Airline with the maximum price

In [ ]:
data[data['price']==1105.000000]

**Q.1. What are the airlines in the dataset, accompanied by their frequencies?**

In [ ]:
data['airline'].nunique()

In [ ]:
data['airline'].unique()

In [ ]:
data['airline'].value_counts(ascending=True)

In [ ]:
# OR
data.airline.value_counts(ascending=True)

In [ ]:
# Showing all the Airlines with their Number of Flights in Horizontal Bar Graph
plt.figure(figsize=(10,6))
data['airline'].value_counts(ascending=True).plot.barh(color=['green','lightblue'])
plt.title('Airline with Frequency')
plt.xlabel('Frequency')
plt.ylabel('Airline')
plt.show()

**Q.2. Show Bar Graphs representing the Departure Time & Arrival Time**

In [ ]:
data.head()

In [ ]:
data['departure_time'].value_counts(ascending=True)  # From the above result, it can be deduced that most flights depart in the morning and least number of flights depart at late night.

In [ ]:
data['arrival_time'].value_counts(ascending=True)  # From the above result, it can be deduced that most flights arrived at night and least number of flights arrived at late night.

In [ ]:
# Viewing our result in a graph
plt.figure(figsize=(16,4))
plt.subplot(1,2,1)
plt.bar(data['departure_time'].value_counts().index,data['departure_time'].value_counts().values,color=['red','orange'])
plt.title('Departure Time of Flight')
plt.xlabel('Departure Time')
plt.ylabel('Frequency')


plt.subplot(1,2,2)
# Viewing our result in a graph
plt.bar(data['arrival_time'].value_counts().index, data['arrival_time'].value_counts().values,color=['blue','purple'])
plt.title('Arrival Time of Flight')
plt.xlabel('Arrival Time')
plt.ylabel('Frequency')
plt.show()

**Q.3. Show Bar Graphs representing the Source City & Destination City**

In [ ]:
data.head()

In [ ]:
data['source_city'].value_counts(ascending=True)  # It can be said from the data below that most of Airines are leaving from Delhi and the least Airlines are leaving from Chennai

In [ ]:
data['destination_city'].value_counts(ascending=True) # It can be deduced that Mumbai is the destination of most of the flight and Chennai is the least destination of the Airline.

In [ ]:
plt.figure(figsize=(16,4))

plt.subplot(1,2,1)

plt.barh(data['source_city'].value_counts().index, data['source_city'].value_counts().values, color=['lightgreen','lightblue'])
plt.title('Source City of Airline')
plt.xlabel('No of Flight')
plt.ylabel('Source City')

plt.subplot(1,2,2)

plt.barh(data['destination_city'].value_counts().index, data['destination_city'].value_counts().values, color=['orange','lightblue'])
plt.title('Destination City of Airline')
plt.xlabel('No of Flight')
plt.ylabel('Destination City')

**Q.4. Does price varies with airlines ?**

In [ ]:
data.head()

In [ ]:
data.groupby('airline')['price'].mean()

In [ ]:
# showing it in a bar chart

plt.figure(figsize=(12,5))
sns.catplot(x='airline', y='price',data=data, kind='bar', palette='rocket', hue='class')
plt.title('Price of Airline')
plt.xlabel('Airline')
plt.show()

**Q.5. Does ticket price change based on the departure time and arrival time?**

In [ ]:
data.head()

In [ ]:
data.groupby('departure_time')['price'].mean()

In [ ]:
data.groupby('arrival_time')['price'].mean()

In [ ]:
plt.figure(figsize=(12,5))
sns.catplot(x='departure_time',y='price',data=data, kind='bar', palette='rocket')
plt.title('Price of Airline based on Departure Time')
plt.xlabel('Departure Time')
plt.show()

In [ ]:
plt.figure(figsize=(12,5))
sns.catplot(x='arrival_time',y='price',data=data, kind='bar', palette='mako')
plt.title('Price of Airline based on Arrival Time')
plt.xlabel('Arrival Time')
plt.show()

In [ ]:
sns.relplot(x='arrival_time', y='price', data=data, col='departure_time', kind='line')

plt.show()

**Q.6. How the price changes with change in Source and Destination?**

In [ ]:
data.head()

In [ ]:
data.groupby('source_city')['price'].mean()

In [ ]:
data.groupby('destination_city')['price'].mean()

In [ ]:
sns.relplot(x='destination_city', y='price', data=data, col='source_city', kind='line')

plt.show()

**Q.7. How is the price affected when tickets are bought in just 1 or 2 days before departure?**

In [ ]:
data.groupby('days_left')['price'].mean()

In [ ]:
sns.relplot(x='days_left', y='price', data=data, kind='line')
plt.show()

**Q.8. How does the ticket price vary between Economy and Business class?**

In [ ]:
data.head()

In [49]:
x=data[data['class']=='Economy']
x

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...
206661,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Economy,13.83,49,7697
206662,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Economy,13.83,49,7709
206663,Vistara,UK-826,Chennai,Afternoon,one,Morning,Hyderabad,Economy,20.58,49,8640
206664,Vistara,UK-822,Chennai,Morning,one,Morning,Hyderabad,Economy,23.33,49,8640
206665,Vistara,UK-824,Chennai,Night,one,Night,Hyderabad,Economy,24.42,49,8640

In [50]:
# To get the mean price of the economy class
x.price.mean()

np.float64(6572.342383362527)

In [51]:
y=data[data['class']=='Business']
y

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
206666,Air_India,AI-868,Delhi,Evening,zero,Evening,Mumbai,Business,2.00,1,25612
206667,Air_India,AI-624,Delhi,Evening,zero,Night,Mumbai,Business,2.25,1,25612
206668,Air_India,AI-531,Delhi,Evening,one,Night,Mumbai,Business,24.75,1,42220
206669,Air_India,AI-839,Delhi,Night,one,Night,Mumbai,Business,26.50,1,44450
206670,Air_India,AI-544,Delhi,Evening,one,Night,Mumbai,Business,6.67,1,46690
...,...,...,...,...,...,...,...,...,...,...,...
300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [52]:
y.price.mean()

np.float64(52540.08112357868)

**Q.9. What will be the Average Price of Vistara airline for a flight from Delhi to Hyderabad in Business Class ?**

In [53]:
data.head(2)

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953

In [56]:
new_class = data[(data['airline']=='Vistara') & (data['source_city']=='Delhi') & (data['destination_city']=='Hyderabad') & (data['class']=='Business')]
new_class

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
219123,Vistara,UK-871,Delhi,Night,zero,Night,Hyderabad,Business,2.33,1,30630
219124,Vistara,UK-879,Delhi,Evening,zero,Evening,Hyderabad,Business,2.25,1,38470
219129,Vistara,UK-955,Delhi,Evening,one,Night,Hyderabad,Business,27.17,1,63513
219130,Vistara,UK-955,Delhi,Evening,one,Afternoon,Hyderabad,Business,18.50,1,65764
219131,Vistara,UK-985,Delhi,Evening,one,Night,Hyderabad,Business,25.08,1,69113
...,...,...,...,...,...,...,...,...,...,...,...
221863,Vistara,UK-963,Delhi,Morning,one,Early_Morning,Hyderabad,Business,23.00,49,53937
221864,Vistara,UK-985,Delhi,Evening,one,Early_Morning,Hyderabad,Business,12.00,49,59537
221865,Vistara,UK-985,Delhi,Evening,one,Afternoon,Hyderabad,Business,16.42,49,59537
221866,Vistara,UK-955,Delhi,Evening,one,Early_Morning,Hyderabad,Business,14.08,49,61889
221867,Vistara,UK-955,Delhi,Evening,one,Afternoon,Hyderabad,Business,18.50,49,61889

In [57]:
new_class.price.mean()

np.float64(47939.840361445786)

In [58]:
print(np.float64(47939.840361445786))

47939.840361445786